{% set name = "unpaddedbase64" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unpaddedbase64-{{ version }}.tar.gz
  sha256: 7273c60c089de39d90f5d6d4a7883a79e319dc9d9b1c8924a7fab96178a5f005

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry-core >=1.0.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - unpaddedbase64
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/unpaddedbase64
  summary: Encode and decode Base64 without "=" padding
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/matrix-org/python-unpaddedbase64

extra:
  recipe-maintainers:
    - goanpeca
